### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Xayanix** [Leymooo/BungeeCord#30]
https://github.com/SpigotMC/BungeeCord/issues/2259

Did you figured out how to fix this issue? 
Thanks

**Comment by Leymooo** [comment]
This is fixed in last bungeecord and spigot. Before fix i have about 3000 kick after fix only 200-300. If you use a via backwards try to update to last dev build.

**Comment by Xayanix** [comment]
Well im using newest Travertine build with 1.12.2 PaperSpigots + latest build of ProtocolSupport and im experiecing time out problems since 1.12 update. Before update i had like ~10 timeouts per day and after its ~150, but my problem is a little bit different than yours was. 

It looks like when players switch server on BungeeCord (concerns proxy join also) then sometimes bungeecord stops to receive and send packets to client as a result player is disconnected by time out. Do you have idea how to investigate it? I think that some exception occurs in bungeecord connection handler (log is clear).

**Comment by Leymooo** [comment]
Just log a input and output keepalive packets and try to analyse what going wrong.
