### ISSUE TITLE
Несовместимость с Litebans

### ISSUE THREAD

**Issue by wasder** [Leymooo/BungeeCord#32]
Мы используем Litebans на бунге. При попытке забаненного игрока зайти на сервер, вместо причины бана, он получает такой экран.
![image](https://user-images.githubusercontent.com/2205216/50522744-94158800-0add-11e9-8d45-c7117244cecd.png)

На обычном Waterfall такой проблемы нет. От разработчика Litebans получили такой комментарий:

> LiteBans doesn't do anything special, just LoginEvent#setCancelled(true) and LoginEvent#setCancelReason().
I don't mess with the protocol so I would assume that a protocol error like that would be caused by BungeeCord itself (maybe compatibility layer), if not another plugin.

**Comment by Leymooo** [comment]
Как будет время, постараюсь разобраться.

**Comment by Leymooo** [comment]
![image](https://user-images.githubusercontent.com/8667294/50705552-dc93ef00-1063-11e9-9fde-7b2103c49638.png)
у меня всё нормально. Проверь ещё раз на последней версии.

**Comment by worldgamings** [comment]
Здравствуйте, можете ли вы помочь мне, как изменить имя сервера bungeecord BotFilter_by_vk.com/Leymooo_s

**Comment by AnchorAnarchyMC** [comment]
on bungee
Bungeecord onlinemode = true
ip:forward = true

on paperspigot
spigot.yml
bungeecord = true

UUID isnt online uuid

**Comment by worldgamings** [comment]
hello
can you help me bungeecord problem [warrning]query maci! how to fixed <3

**Comment by Leymooo** [comment]
@AnchorAnarchyMC, will fix soon.

@worldgamings, you can change BungeeCord in this files: https://github.com/Leymooo/BungeeCord/blob/master/proxy/src/main/java/net/md_5/bungee/BungeeCord.java#L527 , https://github.com/Leymooo/BungeeCord/blob/master/query/src/main/java/net/md_5/bungee/query/QueryHandler.java & https://github.com/Leymooo/BungeeCord/blob/master/query/src/main/java/net/md_5/bungee/query/QueryHandler.java - lines 108 and 128

there is nothing to do with this warnings. there is only one way to fix this - disable query.

**Comment by Leymooo** [comment]
@AnchorAnarchyMC try version 3.7.7-dev

**Comment by worldgamings** [comment]
hownto fix [WARNING] Event PostLoginEvent took 411,130,277,045ns to process for public void me.egg82.altfinder.external.ninja.egg82.events.internal.BungeeAllEventsListener.onPostLoginLow(net.md_5.bungee.api.event.PostLoginEvent)!
> 19:10:11 [WARNING] Event PostLoginEvent(player=WlfCraft) took 411,131,710,910ns to process!

**Comment by worldgamings** [comment]
@Leymooo  plz discord add me BYHH#3795 help me

**Comment by worldgamings** [comment]
Query - Incorrect magic how to fixed
