### ISSUE TITLE
Странная ошибка при входе игрока

### ISSUE THREAD

**Issue by SPYmesu** [Leymooo/BungeeCord#33]
![image](https://user-images.githubusercontent.com/25279760/56481351-aaea4b00-64cf-11e9-9501-9af186545272.png)
В итоге имеем кик по этой причине, и очень частый:
![image](https://user-images.githubusercontent.com/25279760/56481397-d66d3580-64cf-11e9-8f44-9ce094bf60ed.png)

**Comment by Leymooo** [comment]
А viaversion стоит на бандже?

**Comment by SPYmesu** [comment]
Нет, только votifier и наше ядро

**Comment by Leymooo** [comment]
Если честно, то я не знаю из-за чего это. У меня такое было и у других когда ViaVersion  стояла на бандже. Может у вас есть какието манипуляции с протоколом в плагине, например какой нибудь листенер пакетов?

**Comment by SPYmesu** [comment]
Нет, манипуляций с пакетами нет

**Comment by Leymooo** [comment]
эта ошибка всё ещё есть?

**Comment by SPYmesu** [comment]
Выяснили, что ошибка не связана с BotFilter. Простите за беспокойство.
