### ISSUE TITLE
Аудио отпечаток

### ISSUE THREAD

**Issue by ghost** [Leymooo/BungeeCord#36]
Сделайте такую защиту. 

Audio fingerprint

**Comment by Leymooo** [comment]
Это же не возможно реализовать без модификации клиента.

**Comment by ghost** [comment]
@Leymooo доступа к аудио устройствам нет?

**Comment by Leymooo** [comment]
И каким образом я получу доступ к аудио устройствам на клиенте через BungeeCord?
