### ISSUE TITLE
Language ENG support

### ISSUE THREAD

**Issue by LucidAPs** [Leymooo/BungeeCord#53]
Any chance we could get English translation support?

**Comment by LucidAPs** [comment]
I am also getting this error.
https://pastebin.com/raw/veKF9zu4

**Comment by loperd** [comment]
You can fork and translate into English. What is the problem?

**Comment by Loyisa** [comment]
> Any chance we could get English translation support?

https://github.com/DionaMC/BungeeCord-BotFilter-ENG

**Comment by NoJokeFNA** [comment]
@Leymooo Can be closed too.

**Comment by Leymooo** [comment]
I dont have plans to add multi languages support
