### ISSUE TITLE
Captcha check if server is whitelisted

### ISSUE THREAD

**Issue by markovav-official** [Leymooo/BungeeCord#54]
Hello!
I'm using BungeeCord with built in AntiBot protection. Can you add function, which allows to remove captcha check? If server is whitelisted, captcha check is not necessary. So it would be better if antibot will be more customizable. Thanks in advance.

**Comment by Anarchist-byte** [comment]
There is an option in BotFilter config to turn off captcha actually.
Check BotFilter folder, here u'll find file config.yml.In this file u can turn captcha off:
**protection:
    normal: 1**
