### ISSUE TITLE
java.lang.IllegalStateException: Adding 1 elements would exceed capacity of 128

### ISSUE THREAD

**Issue by Dymeth** [Leymooo/BungeeCord#55]
Добрый день.
Установлена последняя версия фильтра из Actions.
Похоже, при определённых действиях со стороны игрока возникает следующее исключение: https://pastebin.com/raw/4aGSSYTY
Ранее также наблюдались подобные исключения - с 2-5 айпи адресов каждый день.
Также ранее capacity была равна 64 вместо 128, небольшие отличия в стеке тоже имеются. Скорее всего, это происходило на более старой версии. Жёлтым старая, залёным новая (последняя):
![image](https://user-images.githubusercontent.com/21080646/83745684-967ef880-a666-11ea-95fe-27bef7442fb7.png)
Версия Java тоже отличалась, но, думаю, это повлияло лишь на точку входа в приложение.

**Comment by CactiChameleon9** [comment]
I am getting this issue also with normal bungeecord.. does this for fix that?

**Comment by Leymooo** [comment]
> I am getting this issue also with normal bungeecord.. does this for fix that?

No. This is fix for another issue.

You should create issue on BungeeCord repo.

**Comment by CactiChameleon9** [comment]
OK... thanks for the reply :D

**Comment by Dymeth** [comment]
Уже достаточно давно не наблюдал данную проблему. Будем считать, что вопрос решён. Спасибо
