### ISSUE TITLE
Появление проблемы с вводом капчи при входе на сервер 

### ISSUE THREAD

**Issue by chudnoffsky** [Leymooo/BungeeCord#56]
В данный момент проблема обнаружена на версиях 1.14.4 и 1.8.9 оптифайн. Не исключено что есть и на других. Происходит редко.
![Screenshot_122](https://user-images.githubusercontent.com/43936464/85999161-c4185100-ba1c-11ea-8d20-8d13f49b9fc1.png)
![Screenshot_119](https://user-images.githubusercontent.com/43936464/85999237-dd210200-ba1c-11ea-9444-b743bc0c8fb3.png)
![Screenshot_126](https://user-images.githubusercontent.com/43936464/85999348-05106580-ba1d-11ea-941d-5a3faeafb9c6.png)

**Comment by gomin1d** [comment]
тоже самое

**Comment by Leymooo** [comment]
Ну тут пару вариантов, либо белый цвет выпал для шрифта, либо по какойто причине не отрисовывается какойто из этих шрифтов https://github.com/Leymooo/BungeeCord/blob/master/proxy/src/main/java/ru/leymooo/botfilter/captcha/CaptchaGeneration.java#L27 (но помоему оно должно на какойто из доступных ссылаться, если такого шрифта нет в системе).

Поидее белого цвета не должно быть, и должен быть 180 180 180 вместо него, но как варик его тоже не видно на карте ( как писали токо под углом видно).
https://github.com/Leymooo/BungeeCord/blob/master/proxy/src/main/java/ru/leymooo/botfilter/captcha/generator/map/MapPalette.java#L21.


https://github.com/Leymooo/BungeeCord/blob/master/proxy/src/main/java/ru/leymooo/botfilter/captcha/CaptchaGeneration.java#L42 если тут поидее выпадет 0-3, то поидее это никак не должно повлиять, т.к https://github.com/Leymooo/BungeeCord/blob/master/proxy/src/main/java/ru/leymooo/botfilter/captcha/CaptchaGeneration.java#L42 тут начинает искать похожие цвета с 4 индекса.

Ну или изза оптифайна такие приколы.
