### ISSUE TITLE
java.lang.NullPointerException при генерации капчи

### ISSUE THREAD

**Issue by Ne0shka** [Leymooo/BungeeCord#62]
Version 3.8.1 (15.07.2020, **stable**)
`$ uname -a`
`Linux domain.name 4.9.0-12-amd64 #1 SMP Debian 4.9.210-1+deb9u1 (2020-06-07) x86_64 GNU/Linux`
`$ java -version`
`openjdk version "1.8.0_252"`
`OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_252-b09)`
`OpenJDK 64-Bit Server VM (AdoptOpenJDK)(build 25.252-b09, mixed mode)`
При запуске банжи во всех потоках происходит подобное:
https://hastebin.com/asapujehih

**Comment by Leymooo** [comment]
Попробуй в строке запуска перед -jar добавить   `-Djava.awt.headless=true` или установить через apt `libxtst6` и `libfontconfig1`
