### ISSUE TITLE
Launch Problem

### ISSUE THREAD

**Issue by kopoh** [Leymooo/BungeeCord#63]
Starting BungeeCord...
18:48:01 [INFO] Using mbed TLS based native cipher.
18:48:01 [INFO] Using zlib based native compressor.
18:48:01 [WARNING] Включаю BungeCord BotFilter 1.8.x-1.16.x от vk.com/Leymooo_s (http://rubukkit.org/threads/137038)
18:48:01 [INFO] [BotFilter] Проверяю наличее обновлений
18:48:02 [INFO] [BotFilter] Обновлений не найдено!
18:48:02 [INFO] [BotFilter] Генерирую капчу [0/900]
18:48:03 [INFO] [BotFilter] Генерирую капчу [107/900]
18:48:04 [INFO] [BotFilter] Генерирую капчу [265/900]
18:48:05 [INFO] [BotFilter] Генерирую капчу [413/900]
18:48:06 [INFO] [BotFilter] Генерирую капчу [575/900]
18:48:07 [INFO] [BotFilter] Генерирую капчу [743/900]
18:48:08 [INFO] [BotFilter] Капча сгенерированна за 6,192 мс
18:48:08 [INFO] [BotFilter] Подключаюсь к датабазе...
18:48:08 [INFO] [BotFilter] Подключено (62 мс)
18:48:08 [INFO] [BotFilter] Очищено 0 аккаунтов
18:48:08 [INFO] [BotFilter] Белый список игроков успешно загружен (0)
18:48:08 [INFO] Not on Windows, attempting to use enhanced EpollEventLoop
18:48:09 [INFO] Epoll is working, utilising it!
18:48:09 [INFO] Couldn't detect bungee version. Custom build?
18:48:09 [SEVERE] Exception in thread "main"
18:48:09 [SEVERE] java.lang.ClassCastException: java.lang.String cannot be cast to java.util.Map
18:48:09 [SEVERE]     at net.md_5.bungee.conf.YamlConfig.load(YamlConfig.java:76)
18:48:09 [SEVERE]     at net.md_5.bungee.conf.Configuration.load(Configuration.java:73)
18:48:09 [SEVERE]     at net.md_5.bungee.BungeeCord.start(BungeeCord.java:296)
18:48:09 [SEVERE]     at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:43)
18:48:09 [SEVERE]     at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)

В чем проблема я хлебушек

**Comment by kopoh** [comment]
Версия 3.8.1- стабильная   (BungeeCord-BotFilter)

**Comment by Leymooo** [comment]
ты гдето в конфиге банжи напортачил

**Comment by kopoh** [comment]
понял, спасибо, сейчас переделаю
