### ISSUE TITLE
Просьба добавить поддержку Geyser

### ISSUE THREAD

**Issue by FeozRu** [Leymooo/BungeeCord#67]
В данный момент на последней стабильной версии при попытке зайти с Bedrock edition, игрок не может пройти проверку на бота по Failed position check. Прошу, по возомжности, учитывать пакеты, получаемые через Geyser при их проверке. Если это невозможно, то прошу прощения за потраченное время

**Comment by Anarchist-byte** [comment]
У меня все работает отлично...
