### ISSUE TITLE
Проблемчик

### ISSUE THREAD

**Issue by Freddereck** [Leymooo/BungeeCord#69]
19:11:24 [SEVERE]     at java.awt.GraphicsEnvironment.getLocalGraphicsEnvironment(GraphicsEnvironment.java:82)
19:11:24 [SEVERE]     at java.awt.image.BufferedImage.createGraphics(BufferedImage.java:1181)
19:11:24 [SEVERE]     at java.awt.image.BufferedImage.getGraphics(BufferedImage.java:1170)
19:11:24 [SEVERE]     at ru.leymooo.botfilter.captcha.generator.CaptchaPainter.draw(CaptchaPainter.java:44)
19:11:24 [SEVERE]     at ru.leymooo.botfilter.captcha.CaptchaGeneration.lambda$generateImages$0(CaptchaGeneration.java:45)
19:11:24 [SEVERE]     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
19:11:24 [SEVERE]     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
19:11:24 [SEVERE]     at java.lang.Thread.run(Thread.java:748)
19:11:24 [SEVERE] Exception in thread "pool-1-thread-823" 
19:11:24 [SEVERE] java.lang.NoClassDefFoundError: Could not initialize class sun.awt.X11GraphicsEnvironment
19:11:24 [SEVERE]     at java.lang.Class.forName0(Native Method)
19:11:24 [SEVERE]     at java.lang.Class.forName(Class.java:264)
19:11:24 [SEVERE]     at java.awt.GraphicsEnvironment.createGE(GraphicsEnvironment.java:103)
19:11:24 [SEVERE]     at java.awt.GraphicsEnvironment.getLocalGraphicsEnvironment(GraphicsEnvironment.java:82)
19:11:24 [SEVERE]     at java.awt.image.BufferedImage.createGraphics(BufferedImage.java:1181)
19:11:24 [SEVERE]     at java.awt.image.BufferedImage.getGraphics(BufferedImage.java:1170)
19:11:24 [SEVERE]     at ru.leymooo.botfilter.captcha.generator.CaptchaPainter.draw(CaptchaPainter.java:44)
19:11:24 [SEVERE]     at ru.leymooo.botfilter.captcha.CaptchaGeneration.lambda$generateImages$0(CaptchaGeneration.java:45)
19:11:24 [SEVERE]     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
19:11:24 [SEVERE]     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
19:11:24 [SEVERE]     at java.lang.Thread.run(Thread.java:748)
19:11:24 [SEVERE] Exception in thread "pool-1-thread-824" 
19:11:24 [SEVERE] java.lang.NoClassDefFoundError: Could not initialize class sun.awt.X11GraphicsEnvironment
19:11:24 [SEVERE]     at java.lang.Class.forName0(Native Method)
19:11:24 [SEVERE]     at java.lang.Class.forName(Class.java:264)
19:11:24 [SEVERE]     at java.awt.GraphicsEnvironment.createGE(GraphicsEnvironment.java:103)
19:11:24 [SEVERE]     at java.awt.GraphicsEnvironment.getLocalGraphicsEnvironment(GraphicsEnvironment.java:82)
19:11:24 [SEVERE]     at java.awt.image.BufferedImage.createGraphics(BufferedImage.java:1181)
19:11:24 [SEVERE]     at java.awt.image.BufferedImage.getGraphics(BufferedImage.java:1170)
19:11:24 [SEVERE]     at ru.leymooo.botfilter.captcha.generator.CaptchaPainter.draw(CaptchaPainter.java:44)
19:11:24 [SEVERE]     at ru.leymooo.botfilter.captcha.CaptchaGeneration.lambda$generateImages$0(CaptchaGeneration.java:45)
19:11:24 [SEVERE]     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
19:11:24 [SEVERE]     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
19:11:24 [SEVERE]     at java.lang.Thread.run(Thread.java:748)
19:11:24 [SEVERE] Exception in thread "pool-1-thread-825"

**Comment by Leymooo** [comment]
Попробуй чтото из этого:
1) Добавить `-Djava.awt.headless=true` в строку запуска перед `-jar` (`java -Xmx... ... -Djava.awt.headless=true -jar BungeeCord.jar`)
2) Установить `libfontconfig1`  и/или `fontconfig` и/или `libxtst6`  через `apt-get install`

Eng:
1) Add `-Djava.awt.headless=true` to your startup flags (`java -Xmx... ... -Djava.awt.headless=true -jar BungeeCord.jar`)
2) Install `libfontconfig1` and/or `fontconfig` and/or `libxtst6` to your system by using `apt-get install`
