### ISSUE TITLE
BOTFILTER

### ISSUE THREAD

**Issue by kirillopnytop** [Leymooo/BungeeCord#72]
БотФилтер не проверяет файлы и останавливается на этом

**Comment by loperd** [comment]
Лог в студию

**Comment by kirillopnytop** [comment]
![image](https://user-images.githubusercontent.com/63828171/112760453-ac97e400-8fff-11eb-9cec-1d9a5e864837.png)

**Comment by loperd** [comment]
Попробуй
 ```bash 
curl -Lv https://raw.githubusercontent.com/Leymooo/BungeeCord/master/version.txt
```

И сбрось выхлоп

**Comment by Leymooo** [comment]
https://github.com/Leymooo/BungeeCord/actions/runs/695872980
Попробуй этот билд

**Comment by kirillopnytop** [comment]
![image](https://user-images.githubusercontent.com/63828171/112790945-27e1b000-9069-11eb-9ba3-504a395d68ed.png)
ну вот а что такое выхлоп и как его сбросить я хз

**Comment by kirillopnytop** [comment]
а в другой сборке пишет вот это
![image](https://user-images.githubusercontent.com/63828171/112791150-8c047400-9069-11eb-81b8-acd589abe3a5.png)

**Comment by Leymooo** [comment]
> ![image](https://user-images.githubusercontent.com/63828171/112790945-27e1b000-9069-11eb-9ba3-504a395d68ed.png)
> ну вот а что такое выхлоп и как его сбросить я хз

По какойто причине у тебя хост  не может полностью SSL сессию открыть. Клиент (хост) отправляет SSL пакет ClientHello серверу(гитхабу), но возможно чтото случилось из этого
1) Пакет не дошел до сервера
2) Не дошел ответный пакет от сервера

Попробуй отключить Firewall и проверить, если не поможет, то возможно стоит попробовать поиграть со значениями `MTU`  у сетевого интерфейса.

**Comment by loperd** [comment]
Порты закрывал? С помощью iptables либо ufw? Либо закрыл исходящий траффик, либо обратись к провайдеру.

Для теста можешь еще выполнить эту команду:
```
curl -Iv https://google.com
```

И выхлоп(результат выполнения команды) сбрось сюда.
