### ISSUE TITLE
Support java 1.16 for BungeeCord

### ISSUE THREAD

**Issue by RitaSister** [Leymooo/BungeeCord#77]
13:22:21 [WARNING] Включаю BungeCord BotFilter 1.8.x-1.16.x от vk.com/Leymooo_s (http://rubukkit.org/threads/137038)
13:22:21 [SEVERE] Exception in thread "main" 
13:22:21 [SEVERE] java.lang.reflect.InaccessibleObjectException: Unable to make private native java.lang.reflect.Field[] java.lang.Class.getDeclaredFields0(boolean) accessible: module java.base does not "opens java.lang" to unnamed module @2a79781f

13:22:21 [SEVERE] 	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:357)

13:22:21 [SEVERE] 	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)

13:22:21 [SEVERE] 	at java.base/java.lang.reflect.Method.checkCanSetAccessible(Method.java:199)

13:22:21 [SEVERE] 	at java.base/java.lang.reflect.Method.setAccessible(Method.java:193)

13:22:21 [SEVERE] 	at ru.leymooo.botfilter.config.Config.setAccessible(Config.java:420)

13:22:21 [SEVERE] 	at ru.leymooo.botfilter.config.Config.getField(Config.java:307)

13:22:21 [SEVERE] 	at ru.leymooo.botfilter.config.Config.set(Config.java:54)

13:22:21 [SEVERE] 	at ru.leymooo.botfilter.config.Config.set(Config.java:114)

13:22:21 [SEVERE] 	at ru.leymooo.botfilter.config.Config.load(Config.java:99)

13:22:21 [SEVERE] 	at ru.leymooo.botfilter.config.Settings.reload(Settings.java:238)

13:22:21 [SEVERE] 	at ru.leymooo.botfilter.BotFilter.<init>(BotFilter.java:74)

13:22:21 [SEVERE] 	at net.md_5.bungee.BungeeCord.start(BungeeCord.java:280)

13:22:21 [SEVERE] 	at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:43)

13:22:21 [SEVERE] 	at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)

**Comment by Lammendam** [comment]
Same problem.
Added line:
`--illegal-access=permit`
but doesn't help.

**Comment by Leymooo** [comment]
`--illegal-access=permit` works on Java 16 (I tested it), but does not work on Java 17. It should be put before `-jar`
You can also try `--add-opens java.base/java.lang=ALL-UNNAMED --add-opens java.base/java.lang.reflect=ALL-UNNAMED --add-opens java.base/java.lang.invoke=ALL-UNNAMED`
