### ISSUE TITLE
FlameCord based?

### ISSUE THREAD

**Issue by NovaPixell** [Leymooo/BungeeCord#78]
It would be a great idea to integrate this antibot system with [FlameCord ](https://github.com/2lstudios-mc/FlameCord)(based on Waterfall)

**Comment by NoJokeFNA** [comment]
@NovaPixell But why? FlameCord can break some things that are important in the current BotFilter - even if the normal Waterfall is much more stable than FlameCord.

**Comment by NovaPixell** [comment]
> @NovaPixell But why? FlameCord can break some things that are important in the current BotFilter - even if the normal Waterfall is much more stable than FlameCord.

Flamecoord is more optimized and contains some Velocity patches

**Comment by NoJokeFNA** [comment]
So you want a mix of BotFilter & FlameCord or what?

**Comment by NovaPixell** [comment]
Exactly

**Comment by xism4** [comment]
Actually FlameCord isn't more optimizied than Waterfall and doesn't have any velocity patches bc's will need to change all hes license system.

**Comment by andreasdc** [comment]
> It would be a great idea to integrate this antibot system with [FlameCord ](https://github.com/2lstudios-mc/FlameCord)(based on Waterfall)

Good idea
