### ISSUE TITLE
Cant join from 1.17 (Не получается зайти с 1.17. Критическая ошибка)

### ISSUE THREAD

**Issue by danirod12** [Leymooo/BungeeCord#80]
![2021-06-10_12 47 20](https://user-images.githubusercontent.com/69750264/121507918-bff70080-c9ed-11eb-9795-6293a68e4b2f.png)
![2021-06-10_13 05 14](https://user-images.githubusercontent.com/69750264/121507921-c08f9700-c9ed-11eb-82c5-8dbcf6617413.png)
![2021-06-10_13 08 24](https://user-images.githubusercontent.com/69750264/121507922-c08f9700-c9ed-11eb-8e60-511a895eb3b6.png)

Версия подсервера 1.16.5, стоит ProtocolSupport под 1.16.5 и ViaVersion 4.0.0
С Waterfall (BungeeCord от PaperMC team) работает все

**Comment by danirod12** [comment]
Лог сервера:
[12:50:21 INFO]: user[/ip:2090] logged in with entity id 9 at ([auth]x, y, z)
[12:50:21 INFO]: user lost connection: Disconnected
Лог банджи:
12:50:21 [INFO] [user] <-> ServerConnector [auth-1] has connected
12:50:21 [INFO] [user] disconnected with: DecoderException : java.lang.IndexOutOfBoundsException: readerIndex(2) + length(63) exceeds writerIndex(36): AbstractPooledDerivedByteBuf$PooledNonRetainedSlicedByteBuf(ridx: 2, widx: 36, cap: 36/36, unwrapped: PooledUnsafeDirectByteBuf(ridx: 4170, widx: 6584, cap: 65536)) @ io.netty.handler.codec.MessageToMessageDecoder:98

Ошибка после проверки на бота происходит

**Comment by Leymooo** [comment]
Установи этот билд https://github.com/Leymooo/BungeeCord/actions/runs/926297622 и добавь в строку запуска перед -jar **`-Dbotfilter.printallerrors=true`** . Оно должно будет вывести более подробную ошибку.

**Comment by danirod12** [comment]
Большое спасибо!

По ошибке понял, что проблема в `de.themoep.resourcepacksplugin.bungee.packets.ResourcePackSendPacket.read(ResourcePackSendPacket.java:132)`.
Это плагин Bungee Resourcepacks. Видимо, для 1.17 изменился формат пакета для установки ресурс-пака

Проблема решена
