### ISSUE TITLE
Помогите

### ISSUE THREAD

**Issue by SqdGoodlol** [Leymooo/BungeeCord#83]
21:09:20 [SEVERE] Exception in thread "main"
21:09:20 [SEVERE] java.lang.reflect.InaccessibleObjectException: Unable to make private native java.lang.reflect.Field[] java.lang.Class.getDeclaredFields0(boolean) accessible: module java.base does not "opens java.lang" to unnamed module @3d8314f0

21:09:20 [SEVERE]     at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:357)

21:09:20 [SEVERE]     at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)

21:09:20 [SEVERE]     at java.base/java.lang.reflect.Method.checkCanSetAccessible(Method.java:199)

21:09:20 [SEVERE]     at java.base/java.lang.reflect.Method.setAccessible(Method.java:193)

21:09:20 [SEVERE]     at ru.leymooo.botfilter.config.Config.setAccessible(Config.java:420)

21:09:20 [SEVERE]     at ru.leymooo.botfilter.config.Config.getField(Config.java:307)

21:09:20 [SEVERE]     at ru.leymooo.botfilter.config.Config.set(Config.java:54)

21:09:20 [SEVERE]     at ru.leymooo.botfilter.config.Config.set(Config.java:114)

21:09:20 [SEVERE]     at ru.leymooo.botfilter.config.Config.load(Config.java:99)

21:09:20 [SEVERE]     at ru.leymooo.botfilter.config.Settings.reload(Settings.java:238)

21:09:20 [SEVERE]     at ru.leymooo.botfilter.BotFilter.<init>(BotFilter.java:74)

21:09:20 [SEVERE]     at net.md_5.bungee.BungeeCord.start(BungeeCord.java:282)

21:09:20 [SEVERE]     at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:49)

21:09:20 [SEVERE]     at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)

**Comment by SqdGoodlol** [comment]
21:09:19 [INFO] Using standard Java JCE cipher.
21:09:19 [INFO] Using standard Java compressor.
21:09:19 [WARNING] Включаю BungeCord BotFilter 1.8.x-1.17.x от vk.com/Leymooo_s (http://rubukkit.org/threads/137038)
21:09:20 [SEVERE] Exception in thread "main"
21:09:20 [SEVERE] java.lang.reflect.InaccessibleObjectException: Unable to make private native java.lang.reflect.Field[] java.lang.Class.getDeclaredFields0(boolean) accessible: module java.base does not "opens java.lang" to unnamed module @3d8314f0

21:09:20 [SEVERE]     at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:357)

21:09:20 [SEVERE]     at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)

21:09:20 [SEVERE]     at java.base/java.lang.reflect.Method.checkCanSetAccessible(Method.java:199)

21:09:20 [SEVERE]     at java.base/java.lang.reflect.Method.setAccessible(Method.java:193)

21:09:20 [SEVERE]     at ru.leymooo.botfilter.config.Config.setAccessible(Config.java:420)

21:09:20 [SEVERE]     at ru.leymooo.botfilter.config.Config.getField(Config.java:307)

21:09:20 [SEVERE]     at ru.leymooo.botfilter.config.Config.set(Config.java:54)

21:09:20 [SEVERE]     at ru.leymooo.botfilter.config.Config.set(Config.java:114)

21:09:20 [SEVERE]     at ru.leymooo.botfilter.config.Config.load(Config.java:99)

21:09:20 [SEVERE]     at ru.leymooo.botfilter.config.Settings.reload(Settings.java:238)

21:09:20 [SEVERE]     at ru.leymooo.botfilter.BotFilter.<init>(BotFilter.java:74)

21:09:20 [SEVERE]     at net.md_5.bungee.BungeeCord.start(BungeeCord.java:282)

21:09:20 [SEVERE]     at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:49)

21:09:20 [SEVERE]     at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)

**Comment by Leymooo** [comment]
Для запуска на новых версиях Java добавьте эти флаги в строку запуска перед -jar:
`--illegal-access=permit` (не работает на java 17+)
или
`--add-opens java.base/java.lang=ALL-UNNAMED --add-opens java.base/java.lang.reflect=ALL-UNNAMED --add-opens java.base/java.lang.invoke=ALL-UNNAMED` (должно работать на всех версиях)

**Comment by SqdGoodlol** [comment]
А готовый батник можно а то не выходит

**Comment by nosebs** [comment]
Такая же ошибка, добавление флага `--illegal-access=permit` не помогло (версия джавы 16)

**Comment by ghost** [comment]
> А готовый батник можно а то не выходит

`java --add-opens java.base/java.lang=ALL-UNNAMED --add-opens java.base/java.lang.reflect=ALL-UNNAMED --add-opens java.base/java.lang.invoke=ALL-UNNAMED  -Xmx1G -jar ядро.jar`
