### ISSUE TITLE
ПОМОГИТЕ

### ISSUE THREAD

**Issue by skovorodka232** [Leymooo/BungeeCord#85]
08:50:57 [INFO] [BotFilter] Генерирую капчу [491/900]
08:50:58 [INFO] [BotFilter] Генерирую капчу [560/900]
08:50:59 [INFO] [BotFilter] Генерирую капчу [639/900]
08:51:00 [INFO] [BotFilter] Генерирую капчу [714/900]
08:51:01 [INFO] [BotFilter] Генерирую капчу [805/900]
08:51:02 [INFO] [BotFilter] Капча сгенерированна за 13,063 мс
08:51:02 [SEVERE] Exception in thread "main"
08:51:02 [SEVERE] java.lang.ExceptionInInitializerError
08:51:02 [SEVERE] at ru.leymooo.botfilter.caching.CachedExpPackets.create(CachedExpPackets.java:31)
08:51:02 [SEVERE] at ru.leymooo.botfilter.caching.CachedExpPackets.<init>(CachedExpPackets.java:18)
08:51:02 [SEVERE] at ru.leymooo.botfilter.caching.PacketUtils.init(PacketUtils.java:83)
08:51:02 [SEVERE] at ru.leymooo.botfilter.BotFilter.<init>(BotFilter.java:83)
08:51:02 [SEVERE] at net.md_5.bungee.BungeeCord.start(BungeeCord.java:280)
08:51:02 [SEVERE] at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:43)
08:51:02 [SEVERE] at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)
08:51:02 [SEVERE] Caused by: java.lang.RuntimeException: java.lang.reflect.InaccessibleObjectException: Unable to make java.lang.invoke.MethodHandles$Lookup(java.lang.Class) accessible: module java.base does not "opens java.lang.invoke" to unnamed module @57b53f49
08:51:02 [SEVERE] at net.md_5.bungee.protocol.MetaFactoryUtils.createNoArgsConstructorUnchecked(MetaFactoryUtils.java:24)
08:51:02 [SEVERE] at net.md_5.bungee.protocol.Protocol$DirectionData.registerPacket(Protocol.java:621)
08:51:02 [SEVERE] at net.md_5.bungee.protocol.Protocol$DirectionData.access$300(Protocol.java:573)
08:51:02 [SEVERE] at net.md_5.bungee.protocol.Protocol$2.<init>(Protocol.java:239)
08:51:02 [SEVERE] at net.md_5.bungee.protocol.Protocol.<clinit>(Protocol.java:71)
08:51:02 [SEVERE] ... 7 more
08:51:02 [SEVERE] Caused by: java.lang.reflect.InaccessibleObjectException: Unable to make java.lang.invoke.MethodHandles$Lookup(java.lang.Class) accessible: module java.base does not "opens java.lang.invoke" to unnamed module @57b53f49
08:51:02 [SEVERE] at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:357)
08:51:02 [SEVERE] at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
08:51:02 [SEVERE] at java.base/java.lang.reflect.Constructor.checkCanSetAccessible(Constructor.java:188)
08:51:02 [SEVERE] at java.base/java.lang.reflect.Constructor.setAccessible(Constructor.java:181)
08:51:02 [SEVERE] at net.md_5.bungee.protocol.MetaFactoryUtils.constructLookup(MetaFactoryUtils.java:46)
08:51:02 [SEVERE] at net.md_5.bungee.protocol.MetaFactoryUtils.createNoArgsConstructor(MetaFactoryUtils.java:31)
08:51:02 [SEVERE] at net.md_5.bungee.protocol.MetaFactoryUtils.createNoArgsConstructorUnchecked(MetaFactoryUtils.java:18)
08:51:02 [SEVERE] ... 11 more

**Comment by Noop1** [comment]
Для запуска на новых версиях Java (Java 16+) добавьте эти флаги в строку запуска перед -jar:
--illegal-access=permit (не будет на java 17+)
или
--add-opens java.base/java.lang=ALL-UNNAMED --add-opens java.base/java.lang.reflect=ALL-UNNAMED --add-opens java.base/java.lang.invoke=ALL-UNNAMED (должно работать на всех версиях)
