### ISSUE TITLE
Ошибка с JAVA 16

### ISSUE THREAD

**Issue by dudeels** [Leymooo/BungeeCord#91]
[proxy.log](https://github.com/Leymooo/BungeeCord/files/6913632/proxy.log)

**Comment by NoJokeFNA** [comment]
You just need to install fontmanager -> sudo apt-get install font-manager

**Comment by dudeels** [comment]
![image](https://user-images.githubusercontent.com/88294571/127823382-6761a389-3769-4aaf-bef5-b2cf1af86a31.png)

**Comment by NoJokeFNA** [comment]
Remove SkinsRestorer from bungee and use it on your spigot server 🤔
