### ISSUE TITLE
Капча может быть практически не видна из-за слишком светлых цифр

### ISSUE THREAD

**Issue by gomin1d** [Leymooo/BungeeCord#92]
Версия бот фильтра: 3.8.9-dev

Вот какая капча мне попалась (клиент версии 1.12.2):  
![image](https://user-images.githubusercontent.com/32991511/128217310-a3f59ce3-473e-4e2a-9f77-33507e95d5fc.png)

Было бы неплохо исключить все цвета, близкие к белому.

**Comment by NoJokeFNA** [comment]
Can this not be fixed simply by adding the following code here https://github.com/Leymooo/BungeeCord/blob/master/proxy/src/main/java/ru/leymooo/botfilter/captcha/CaptchaGeneration.java#L78:

```java
private Color randomNotWhiteColor()
    {
        Color color = MapPalette.colors[rnd.nextInt( MapPalette.colors.length )];
        color = color.darker(); <----

        if ( color.getRed() == 255 && color.getGreen() == 255 && color.getBlue() == 255 )
        {
            return randomNotWhiteColor();
        }

        if ( color.getRed() == 220 && color.getGreen() == 220 && color.getBlue() == 220 )
        {
            return randomNotWhiteColor();
        }
        return color;
    }
```

🤔

**Comment by gomin1d** [comment]
Опять 
![image](https://user-images.githubusercontent.com/32991511/128714450-7009f5cd-1029-454d-b3a3-1d0a160ac9ab.png)

**Comment by NoJokeFNA** [comment]
Did you recompile the source code with the code I sent you? Or did it just reappear and you wanted to share it with us?

**Comment by gomin1d** [comment]
> Did you recompile the source code with the code I sent you? Or did it just reappear and you wanted to share it with us?

no, I haven't changed the code. I just shared a new incident

**Comment by Leymooo** [comment]
попробуй дев билд, может быть получше станет

**Comment by gomin1d** [comment]
больше жалоб на это не поступала
