### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by ddfigueiras** [Leymooo/BungeeCord#93]
How do i fix this error?
[proxy.log.txt](https://github.com/Leymooo/BungeeCord/files/6993992/proxy.log.txt)

**Comment by Leymooo** [comment]
https://github.com/Leymooo/BungeeCord/issues/69#issuecomment-777761054

**Comment by ddfigueiras** [comment]
Keep giving error:
[proxy.log.txt](https://github.com/Leymooo/BungeeCord/files/7002431/proxy.log.txt)
